// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeatherDashboard.Infrastructure.Data;

#nullable disable

namespace WeatherDashboard.Infrastructure.Data.Migrations
{
    [DbContext(typeof(WeatherDbContext))]
    partial class WeatherDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WeatherDashboard.Domain.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OpenWeatherCityId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("Id");

                    b.HasIndex("Name", "State")
                        .IsUnique();

                    b.ToTable("Cities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Latitude = -9.97499,
                            Longitude = -67.824299999999994,
                            Name = "Rio Branco",
                            State = "AC"
                        },
                        new
                        {
                            Id = 2,
                            Latitude = -9.6659900000000007,
                            Longitude = -35.734999999999999,
                            Name = "Maceió",
                            State = "AL"
                        },
                        new
                        {
                            Id = 3,
                            Latitude = 0.038899999999999997,
                            Longitude = -51.066400000000002,
                            Name = "Macapá",
                            State = "AP"
                        },
                        new
                        {
                            Id = 4,
                            Latitude = -3.1019399999999999,
                            Longitude = -60.024999999999999,
                            Name = "Manaus",
                            State = "AM"
                        },
                        new
                        {
                            Id = 5,
                            Latitude = -12.9711,
                            Longitude = -38.510800000000003,
                            Name = "Salvador",
                            State = "BA"
                        },
                        new
                        {
                            Id = 6,
                            Latitude = -3.7172200000000002,
                            Longitude = -38.543100000000003,
                            Name = "Fortaleza",
                            State = "CE"
                        },
                        new
                        {
                            Id = 7,
                            Latitude = -15.7797,
                            Longitude = -47.929699999999997,
                            Name = "Brasília",
                            State = "DF"
                        },
                        new
                        {
                            Id = 8,
                            Latitude = -20.319400000000002,
                            Longitude = -40.337800000000001,
                            Name = "Vitória",
                            State = "ES"
                        },
                        new
                        {
                            Id = 9,
                            Latitude = -16.686900000000001,
                            Longitude = -49.264800000000001,
                            Name = "Goiânia",
                            State = "GO"
                        },
                        new
                        {
                            Id = 10,
                            Latitude = -2.5297200000000002,
                            Longitude = -44.302799999999998,
                            Name = "São Luís",
                            State = "MA"
                        },
                        new
                        {
                            Id = 11,
                            Latitude = -15.5961,
                            Longitude = -56.096699999999998,
                            Name = "Cuiabá",
                            State = "MT"
                        },
                        new
                        {
                            Id = 12,
                            Latitude = -20.442799999999998,
                            Longitude = -54.6464,
                            Name = "Campo Grande",
                            State = "MS"
                        },
                        new
                        {
                            Id = 13,
                            Latitude = -19.9208,
                            Longitude = -43.937800000000003,
                            Name = "Belo Horizonte",
                            State = "MG"
                        },
                        new
                        {
                            Id = 14,
                            Latitude = -1.45583,
                            Longitude = -48.503900000000002,
                            Name = "Belém",
                            State = "PA"
                        },
                        new
                        {
                            Id = 15,
                            Latitude = -7.1150000000000002,
                            Longitude = -34.863100000000003,
                            Name = "João Pessoa",
                            State = "PB"
                        },
                        new
                        {
                            Id = 16,
                            Latitude = -25.427800000000001,
                            Longitude = -49.273099999999999,
                            Name = "Curitiba",
                            State = "PR"
                        },
                        new
                        {
                            Id = 17,
                            Latitude = -8.0538900000000009,
                            Longitude = -34.881100000000004,
                            Name = "Recife",
                            State = "PE"
                        },
                        new
                        {
                            Id = 18,
                            Latitude = -5.0891700000000002,
                            Longitude = -42.801900000000003,
                            Name = "Teresina",
                            State = "PI"
                        },
                        new
                        {
                            Id = 19,
                            Latitude = -22.9068,
                            Longitude = -43.172899999999998,
                            Name = "Rio de Janeiro",
                            State = "RJ"
                        },
                        new
                        {
                            Id = 20,
                            Latitude = -5.7949999999999999,
                            Longitude = -35.209400000000002,
                            Name = "Natal",
                            State = "RN"
                        },
                        new
                        {
                            Id = 21,
                            Latitude = -30.033100000000001,
                            Longitude = -51.229999999999997,
                            Name = "Porto Alegre",
                            State = "RS"
                        },
                        new
                        {
                            Id = 22,
                            Latitude = -8.7619399999999992,
                            Longitude = -63.9039,
                            Name = "Porto Velho",
                            State = "RO"
                        },
                        new
                        {
                            Id = 23,
                            Latitude = 2.8197199999999998,
                            Longitude = -60.673299999999998,
                            Name = "Boa Vista",
                            State = "RR"
                        },
                        new
                        {
                            Id = 24,
                            Latitude = -27.595400000000001,
                            Longitude = -48.548000000000002,
                            Name = "Florianópolis",
                            State = "SC"
                        },
                        new
                        {
                            Id = 25,
                            Latitude = -23.547499999999999,
                            Longitude = -46.636099999999999,
                            Name = "São Paulo",
                            State = "SP"
                        },
                        new
                        {
                            Id = 26,
                            Latitude = -10.911099999999999,
                            Longitude = -37.0717,
                            Name = "Aracaju",
                            State = "SE"
                        },
                        new
                        {
                            Id = 27,
                            Latitude = -10.2128,
                            Longitude = -48.360300000000002,
                            Name = "Palmas",
                            State = "TO"
                        });
                });

            modelBuilder.Entity("WeatherDashboard.Domain.Entities.WeatherReading", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CollectedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<double>("FeelsLikeC")
                        .HasColumnType("float");

                    b.Property<int>("Humidity")
                        .HasColumnType("int");

                    b.Property<double>("PressureHpa")
                        .HasColumnType("float");

                    b.Property<double>("TempMaxC")
                        .HasColumnType("float");

                    b.Property<double>("TempMinC")
                        .HasColumnType("float");

                    b.Property<double>("TemperatureC")
                        .HasColumnType("float");

                    b.Property<string>("WeatherDescription")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("WeatherIcon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("WindSpeedMs")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CityId", "CollectedAtUtc");

                    b.ToTable("WeatherReadings", (string)null);
                });

            modelBuilder.Entity("WeatherDashboard.Domain.Entities.WeatherReading", b =>
                {
                    b.HasOne("WeatherDashboard.Domain.Entities.City", "City")
                        .WithMany("Readings")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("WeatherDashboard.Domain.Entities.City", b =>
                {
                    b.Navigation("Readings");
                });
#pragma warning restore 612, 618
        }
    }
}
